// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcingYamaha;

#nullable disable

namespace ParcingYamaha.Migrations
{
    [DbContext(typeof(SampleContext))]
    [Migration("20221124192503_parts")]
    partial class parts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParcingYamaha.Modeldatacollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("calledCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelBaseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prodCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prodPictureFileURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prodPictureNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("releaseYymm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("vinNoSearch")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Modeldatacollection");
                });

            modelBuilder.Entity("ParcingYamaha.Partsdatacollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("appSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("modeldatacollectionID")
                        .HasColumnType("int");

                    b.Property<string>("partName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partNewsFileURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("refNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("selectableId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("modeldatacollectionID");

                    b.ToTable("Partsdatacollection");
                });

            modelBuilder.Entity("ParcingYamaha.Partsdatacollection", b =>
                {
                    b.HasOne("ParcingYamaha.Modeldatacollection", "modeldatacollection")
                        .WithMany()
                        .HasForeignKey("modeldatacollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("modeldatacollection");
                });
#pragma warning restore 612, 618
        }
    }
}
